export const ALL_DESIGN_REQUEST = "ALL_DESIGN_REQUEST";
export const ALL_DESIGN_SUCCESS = "ALL_DESIGN_SUCCESS";
export const ALL_DESIGN_FAIL = "ALL_DESIGN_FAIL";

export const SINGLE_DESIGN_REQUEST = "SINGLE_DESIGN_REQUEST";
export const SINGLE_DESIGN_SUCCESS = "SINGLE_DESIGN_SUCCESS";
export const SINGLE_DESIGN_FAIl = "SINGLE_DESIGN_FAIL";

export const DELETE_DESIGN_REQUEST = "DELETE_DESIGN_REQUEST";
export const DELETE_DESIGN_SUCCESS = "DELETE_DESIGN_SUCCESS";
export const DELETE_DESIGN_RESET = "DELETE_DESIGN_RESET";
export const DELETE_DESIGN_FAIL = "DELETE_DESIGN_FAIL";

export const CREATE_DESIGN_REQUEST = "CREATE_DESIGN_REQUEST";
export const CREATE_DESIGN_SUCCESS = "CREATE_DESIGN_SUCCESS";
export const CREATE_DESIGN_RESET = "CREATE_DESIGN_RESET";
export const CREATE_DESIGN_FAIl = "CREATE_DESIGN_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";